services:
    frontend:
        container_name: development
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        volumes:
            - .:/usr/src/app/frontend
            - /usr/src/app/frontend/node_modules
            - /usr/src/app/frontend/.next
        environment:
            - NODE_ENV=development
            - WATCHPACK_POLLING=true
            - NEXT_TELEMETRY_DISABLED=1
        command: ['npm', 'run', 'dev']
