services:
    backseat-90:
        container_name: development
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        volumes:
            # - .:/home/frontend:delegated
            - .:/home/frontend
            - /home/frontend/node_modules
            - /home/frontend/.next
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
            - WATCHPACK_POLLING=true
        command: ['npm', 'run', 'dev']
